export { default as DownloadsSectionIcon } from './downloads-section-icon';
export { default as DefaultDownloadsIcon } from './default-downloads-icon';
export { default as TopFeaturedArticlesIcon } from './top-featured-articles-icon';
export { default as SearchIcon } from './search-icon';
export { default as LoaderIcon } from './loader-icon';
export { default as MenuIcon } from './menu-icon';
export { default as InstagramIcon } from './instagram-icon';
export { default as FacebookIcon } from './facebook-icon';
export { default as LinkedInIcon } from './linkedin-icon';
export { default as TelegramIcon } from './telegram-icon-1';
export { default as TelegramIcon2} from './telegram-icon-2';
export { default as TelegramAlternativeIcon } from './telegram-icon';
export { default as Wave } from './wave';
